### ISSUE TITLE
Docker Container --help 

### ISSUE THREAD

**Issue by purcell3a** [howstrongiam/backend#1]
- the graphql schema to be generated is being written by me right now 

- A basic docker container is setup -> db table is made (**postgres**) 
 
 The problem is the docker container continuously exits out for various reasons and I can't get it to run 
 
 I'm also trying to figure out how to interact with gql-gen and getting it to re-generate (or just run) when I add more information inside of the docker container 
 
 once this is fixed some basic instructions for how to interact with the database etc is needed

PRECEDES [this issue ](https://github.com/howstrongiam/backend/issues/2)

**Comment by iam-mateen** [comment]
Docker Compose file is working correctly, starting both service and postgres.
